pdpostdata/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from photos.forms import PhotoSortForm, CartItemForm, PhotoUploadForm
from photos.views import UploadPhotosWizard
from dashboards.views import AnalyticsIndexView
from products import views

from django.contrib.admin.views.decorators import staff_member_required

from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets


# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')


# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'products', views.ProductViewSet)

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^wizard/(?P<slug>[\w-]+)/$', UploadPhotosWizard.as_view([PhotoUploadForm, PhotoSortForm, CartItemForm]), name='wizard'),
    url(r'^wizard/edit/(?P<cart_item_id>\d+)/$', 'photos.views.edit_wizard', name='edit_wizard'),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^accounts/password_change/$', 'django.contrib.auth.views.password_change',
        {'post_change_redirect': '/accounts/password_change/done/'},
        name="password_change"),
    url(r'^accounts/password_change/done/$',
        'django.contrib.auth.views.password_change_done'),

    url(r'^$', 'products.views.home', name='home'),
    url(r'^s/$', 'products.views.search', name='search'),
    url(r'^products/$', 'products.views.all', name='products'),
    url(r'^products/(?P<slug>[\w-]+)/$', 'products.views.single', name='single_product'),

    url(r'^cart/(?P<id>\d+)/$', 'carts.views.remove_from_cart', name='remove_from_cart'),
    url(r'^cart/(?P<slug>[\w-]+)/$', 'carts.views.add_to_cart', name='add_to_cart'),
    url(r'^cart/$', 'carts.views.view', name='cart'),

    url(r'^checkout/$', 'orders.views.checkout', name='checkout'),
    url(r'^orders/$', 'orders.views.orders', name='user_orders'),
    url(r'^ajax/rate_order/$', 'orders.views.rate_order', name='ajax_rate_order'),
    # url(r'^orders/(?P<order_id>[\w-]+)/$', 'orders.views.order_details', name='order_details'),

    url(r'^ajax/dismiss_marketing_message/$', 'marketing.views.dismiss_marketing_message',
        name='dismiss_marketing_message'),
    url(r'^ajax/email_signup/$', 'marketing.views.email_signup', name='ajax_email_signup'),
    url(r'^ajax/add_user_address/$', 'accounts.views.add_user_address', name='ajax_add_user_address'),

    url(r'^accounts/logout/$', 'accounts.views.logout_view', name='auth_logout'),
    url(r'^accounts/login/$', 'accounts.views.login_view', name='auth_login'),
    url(r'^accounts/register/$', 'accounts.views.registration_view', name='auth_register'),
    url(r'^accounts/address/add/$', 'accounts.views.add_user_address', name='add_user_address'),
    url(r'^accounts/activate/(?P<activation_key>\w+)/$', 'accounts.views.activation_view', name='activation_view'),
    url(r'^accounts/profile/$', 'accounts.views.user_profile', name='user_profile'),
    url(r'^address/delete/(?P<address_id>\d+)/$', 'accounts.views.delete_user_address', name='delete_user_address'),
    url(r'^helpticket/send_helpticket/$', 'helptickets.views.send_helpticket', name='send_helpticket'),

    url(r'^photos/upload/$', 'photos.views.upload', name='upload'),
    url(r'^upload2/(?P<slug>[\w-]+)/$', 'photos.views.make', name='upload2'),
    url(r'^make/(?P<slug>[\w-]+)/$', 'photos.views.make', name='make'),
    url(r'^crop/$', 'photos.views.crop_image', name='cropper'),
    url(r'^sort/$', 'photos.views.sort_photos', name='sort_photos'),
    url(r'^delete_uploaded_image/$', 'photos.views.delete_uploaded_image', name='delete_uploaded_image'),

    url(r'^dashboard/$', staff_member_required(AnalyticsIndexView.as_view()), name='dashboard'),
    url(r'^dashboard/orders/$', 'dashboards.views.orders', name='dashboard_orders'),
    url(r'^dashboard/orders/(?P<order_id>[\w-]+)/download/$', 'dashboards.views.send_zipfile', name='send_zipfile'),
    url(r'^dashboard/users/$', 'dashboards.views.users', name='dashboard_users'),
    url(r'^dashboard/reports/$', 'dashboards.views.reports', name='dashboard_reports'),
    url(r'^dashboard/helptickets/$', 'dashboards.views.helptickets', name='dashboard_helptickets'),
    url(r'^dashboard/helptickets/answer/$', 'dashboards.views.answer_help_ticket', name='dashboard_answer_help_ticket'),


    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^upload_from_instagram/(?P<product_slug>[\w-]+)/$', 'photos.views.upload_instagram_images', name='upload_instagram_images'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/models.py
import os

from django.db import models

# Create your models here.
from products.models import Product, Variation


def get_image_path(instance, filename):
    return os.path.join('cart_item/images', str(instance.cart_item), filename)


class Cart(models.Model):
    total = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)

    def __unicode__(self):
        return "Cart id: %s" % self.id


class CartItem(models.Model):
    cart = models.ForeignKey('Cart', null=True, blank=True)
    product = models.ForeignKey(Product)
    variations = models.ManyToManyField(Variation, blank=True)
    quantity = models.IntegerField(default=1)
    line_total = models.DecimalField(default=10.99, max_digits=10, decimal_places=2)
    notes = models.TextField(null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __unicode__(self):
        try:
            return "Cart id: %s" % str(self.cart.id) + " - " + "Product name: %s" % self.product.title
        except:
            return self.product.title

photos/models.py
import StringIO
import uuid
from imagekit.models import ImageSpecField
import os
from os.path import sep
from PIL import Image, ImageFilter
from django.core.exceptions import ValidationError

from django.utils.translation import ugettext_lazy as _

from django.db import models
from pilkit.processors import SmartResize, ResizeToFill, TrimBorderColor, Resize, ResizeToFit, Transpose
from carts.models import CartItem
from photos.storage import OverwriteStorage

nearest_int = lambda a: int(round(a))
to_retina_path = lambda p: '%s@2x%s' % os.path.splitext(p)


def make_uuid():
    random = str(uuid.uuid4())  # Convert UUID format to a Python string.
    random = random.replace("-", "")  # Remove the UUID '-'.
    return random


def get_image_path(instance, filename):
    """Returns a random string of length string_length."""
    # random =  str(uuid.uuid4()) # Convert UUID format to a Python string.
    # random = random.replace("-","") # Remove the UUID '-'.
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (str(instance.id), ext)
    return os.path.join('uploads', filename)


# class SizeSet(models.Model):
#     name = models.CharField(max_length=255, db_index=True)
#     slug = models.SlugField(max_length=50, null=False, unique=True)
#
#     def __unicode__(self):
#         return u"%s" % self.name
#
#     def get_size_by_ratio(self):
#         """ Shorthand to get all the unique ratios for display in the admin,
#         rather than show every possible thumbnail
#         """
#
#         size_query = Size.objects.filter(size_set__id=self.id)
#         size_query.query.group_by = ["aspect_ratio"]
#         try:
#             return size_query
#         except ValueError:
#             return None
#
#
# class Size(models.Model):
#     # An Size not associated with a set is a 'one off'
#     size_set = models.ForeignKey(SizeSet, null=True)
#
#     date_modified = models.DateTimeField(auto_now=True, null=True)
#
#     name = models.CharField(max_length=255, db_index=True)
#
#     slug = models.SlugField(max_length=50, null=False)
#
#     height = models.PositiveIntegerField(null=True, blank=True)
#
#     width = models.PositiveIntegerField(null=True, blank=True)
#
#     aspect_ratio = models.FloatField(null=True, blank=True)
#
#     auto_crop = models.BooleanField(default=False)
#
#     retina = models.BooleanField(default=False)
#
#     def get_height(self):
#         """
#         Return calculated height, if possible.
#         @return: Height
#         @rtype: positive int
#         """
#         if self.height is None and self.width and self.aspect_ratio:
#             return nearest_int(self.width / self.aspect_ratio)
#
#         return self.height
#
#     def get_width(self):
#         """
#         Returns calculate width, if possible.
#         @return: Width
#         @rtype: positive int
#         """
#         if self.width is None and self.height and self.aspect_ratio:
#             return nearest_int(self.height * self.aspect_ratio)
#
#         return self.width
#
#     def get_aspect_ratio(self):
#         """
#         Returns calculated aspect ratio, if possible.
#         @return: Aspect Ratio
#         @rtype:  float
#         """
#         if self.aspect_ratio is None and self.height and self.width:
#             return round(self.width / float(self.height), 2)
#
#         return self.aspect_ratio
#
#     def get_dimensions(self):
#         """
#         Returns all calculated dimensions for the size.
#         @return: width, height, aspect ratio
#         @rtype: (int > 0, int > 0, float > 0)
#         """
#         return (self.get_width(), self.get_height(), self.get_aspect_ratio())
#
#     def calc_dimensions(self, width, height):
#         """
#         From a given set of dimensions, calculates the rendered size.
#         @param width: Starting width
#         @type  width: Positive int
#         @param height: Starting height
#         @type  height: Positive int
#         @return: rendered width, rendered height
#         @rtype: (Width, Height)
#         """
#         w, h, a = self.get_dimensions()
#         # Explicit dimension give explicit answers
#         if w and h:
#             return w, h, a
#
#         # Empty sizes are basically useless.
#         if not (w or h):
#             return width, height, None
#
#         aspect_ratio = round(width / float(height), 2)
#         if w:
#             h = nearest_int(w / aspect_ratio)
#         else:
#             w = nearest_int(h * aspect_ratio)
#
#         return w, h, round(w / float(h), 2)
#
#     def __unicode__(self):
#         return u"%s: %sx%s" % (self.name, self.width, self.height)
#
#     def save(self, *args, **kwargs):
#         if self.slug is None:
#             self.slug = uuid.uuid4().hex
#         w, h, a = self.get_dimensions()
#         self.width = w
#         self.height = h
#         self.aspect_ratio = a
#         super(Size, self).save(*args, **kwargs)


# Create your models here.
class Photo(models.Model):
    id = models.CharField(max_length=36, primary_key=True, default=make_uuid)
    temp_hash = models.CharField(max_length='255')
    message = models.TextField(max_length='120', blank=True)
    image = models.ImageField(upload_to=get_image_path, storage=OverwriteStorage())
    smart = ImageSpecField(
        source='image', processors=[Transpose(), ResizeToFit(768, 768)], format='JPEG', options={'quality': 80})
    thumbnail = ImageSpecField(
        source='image', processors=[Transpose(), ResizeToFill(120, 120)], format='JPEG',
        options={'quality': 80})
    sequence = models.PositiveSmallIntegerField(default=0, null=True, blank=True)
    cart_item = models.ForeignKey(CartItem, null=True, blank=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __unicode__(self):
        return str(id)

    def get_name(self, prefix=None):
        """Strips the name of a file into (pathname, extension)"""
        # Get the filename from the original image field, i.e: "image.jpg"
        filename = self.image.path.split(sep)[-1]
        # Get the extension of the original image
        ext = filename.split('.')[-1]

        return "%s%s.%s" % (prefix, str(self.id), ext)

    def crop_photo(self, crop_box=None):
        try:
            img = Image.open(self.image.path, mode='r')

            x = crop_box['x']
            y = crop_box['y']
            width = crop_box['width']
            height = crop_box['height']

            values = (x, y, x + width, y + height)

            if width and height and (width != img.size[0] or height != img.size[1]):
                cropped_image = img.crop(values).resize((width, height), Image.ANTIALIAS)
            else:
                raise

            # Get the filename from the original image field, i.e: "image.jpg"
            filename = self.get_name("crop_")
            tempfile_io = StringIO.StringIO()
            cropped_image.save(tempfile_io, format='JPEG', overwrite=True)
            # from django.core.files.uploadedfile import InMemoryUploadedFile
            from django.core.files.images import ImageFile

            image_file = ImageFile(tempfile_io, filename)
            # image_file = InMemoryUploadedFile(tempfile_io, None, 'crop.jpg', 'image/jpeg', tempfile_io.len, None)

            return image_file
        except IOError:
            raise ValidationError("Error, no se pudo abrir el archivo de imagen")


class Cropped(models.Model):
    """
    Cropped segment of original image
    """
    original = models.OneToOneField(Photo, related_name='cropped', verbose_name=_('Original image'),
                                    on_delete=models.CASCADE)
    image_cropped = models.ImageField(_('Image'), upload_to='uploads/', editable=False)
    smart = ImageSpecField(
        source='image_cropped', processors=[Transpose(), ResizeToFit(600, 600)], format='JPEG', options={'quality': 80})
    thumbnail = ImageSpecField(
        source='image_cropped', processors=[Transpose(), ResizeToFill(120, 120)], format='JPEG',
        options={'quality': 80})
    x = models.PositiveIntegerField(_('offset X'), default=0)
    y = models.PositiveIntegerField(_('offset Y'), default=0)
    w = models.PositiveIntegerField(_('cropped area width'), blank=True, null=True)
    h = models.PositiveIntegerField(_('cropped area height'), blank=True, null=True)

    def __str__(self):
        return u'%s-%sx%s' % (self.original, self.w, self.h)

    def __unicode__(self):
        return u"Crop: (%i, %i),(%i, %i) " % (
            self.crop_x,
            self.crop_y,
            self.crop_x + self.crop_w,
            self.crop_y + self.crop_h,
        )

    def save(self, *args, **kwargs):
        # delete old file when replacing by updating the file
        try:
            this = Cropped.objects.get(id=self.id)
            if this.image_cropped != self.image_cropped:
                this.image_cropped.delete(save=False)
        except Cropped.DoesNotExist:
            pass  # when new photo then we do nothing, normal case
        except Exception as e:
            raise e
        super(Cropped, self).save(*args, **kwargs)

# import cImage as image
# from math import sqrt
# from os.path import splitext
#
#
# class ImageFilter(object):
#     def __init__(self, img_file, draw=1):
#         """Initialize image, clone it, get its size and create a canvas"""
#         self.img_file = img_file
#         self.oldimg = image.Image(self.img_file)
#         self.width = self.oldimg.getWidth()
#         self.height = self.oldimg.getHeight()
#         self.newimg = self.oldimg.copy()
#         # Decides whether to skip drawing the image in a popup window.
#         self.draw = draw
#         if self.draw:
#             self.win = image.ImageWin(self.img_file, self.width, self.height)
#
#     def write(self, func_name="_", draw=1):
#         """Draw and save a processed image"""

templates/carts/view.html
{% extends 'base.html' %}

{% block content %}

    {% if empty %}
        <div class='container-fluid'>
            <div class="row">
                    <div class="blockquote-box blockquote-primary clearfix">
                <div class="square pull-left">
                    <span class="fa fa-shopping-cart glyphicon-lg"></span>
                </div>
                <h1 class="message text-center">{{ empty_message }}</h1>
            </div>
            </div>
        </div>

    {% else %}
        <div class='container'>
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Producto</th>
                            <th class="text-center">Cantidad</th>
                            <th class="text-center">Precio</th>
                            <th class="text-center">Fotos</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for item in cart.cartitem_set.all %}
                        <tr>
                        <td class="col-md-2">
                            {% for product_image in item.product.product_images.all %}
                                {% if product_image.featured %}
                                    <img src="{{ product_image.image.url }}" class="img-responsive">
                                {% endif %}
                            {% endfor %}
                        </td>
                            <td class="col-sm-8 col-md-6">
                                <h5><a href="{% url 'edit_wizard' item.id %}">{{ item.product }}</a></h5>
                            </td>
                            <td  style="text-align: center">
                                <input type="number" class="form-control" id="qty" value="{{ item.quantity }}">
                            </td>
                            <td class="col-sm-3 col-md-2 text-center"><h5>Bs.F {{ item.product.price }}</h5></td>
                            <td class="col-sm-1 col-md-1 text-center"><h5>{{ item.photo_set.count }}</h5></td>
                            <td class="col-sm-1 col-md-1">
                                <a href='{% url "remove_from_cart" item.id %}'>
                                    <button class="btn btn-danger">Eliminar <span class="glyphicon glyphicon-remove"></span> </button>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><h4>Total</h4></td>
                            <td class="text-right"><h4><strong>Bs.F {{ cart.total }}</strong></h4></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td class="col-sm-1 col-md-1 text-center">
                                <a class="btn btn-default btn-responsive" href="{% url 'products' %}">
                                    <span class="glyphicon glyphicon-shopping-cart"></span> Continuar comprando
                                </a>
                            </td>
                            <td class="col-sm-1 col-md-1 text-center">
                                <a class="btn btn-success btn-responsive btn-fill" href="{% url 'checkout' %}"> Checkout
                                    <span class="glyphicon glyphicon-play"></span>
                                </a>
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>

    <!--<div class="table-responsive">
        <table class='table'>
            <thead>
                <th>Producto</th>
                <th>Precio</th>
                <th>Cantidad</th>
                <th>Fotos</th>
                <th></th>
            </thead>
            {% for item in cart.cartitem_set.all %}
            <tbody>
            <tr>
                <td class="col-sm-8 col-md-6">{{ item.product }} {% if item.variations.all %}<ul>{% for subitem in item.variations.all %}<li>{{ subitem.category|capfirst}} : {{ subitem.title|capfirst }}{% endfor %}</li><ul> {% endif %}</td>
                <td>Bs.F {{ item.product.price }}</td>
                <td>{{ item.quantity }}</td>
                <td>{{ item.photo_set.count }}</td>
                <td class="text-right">
                    <a class="btn btn-danger btn-responsive" href="{% url 'remove_from_cart' item.id %}">
                    <span class="glyphicon glyphicon-remove"></span>
                    </a>
                </td>
            </tr>

            {% endfor %}
        </tbody>
            <tfoot>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td><h4>Total</h4></td>
                <td><h4>Bs.F {{ cart.total }}</h4></td>
            </tr>
            </tfoot>

        </table>
        </div>

        <a class="btn btn-default btn-responsive" href="{% url 'products' %}">
            <span class="glyphicon glyphicon-shopping-cart"></span> Continuar comprando
        </a>
        <a class="btn btn-success btn-responsive" href="{% url 'checkout' %}">
            <span class="glyphicon glyphicon-play"></span> Checkout
        </a> -->

        </div>
    {% endif %}

{% endblock %}