pdpostdata/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from photos.forms import PhotoSortForm, CartItemForm, PhotoUploadForm
from photos.views import UploadPhotosWizard
from dashboards.views import AnalyticsIndexView
from products import views

from django.contrib.admin.views.decorators import staff_member_required

from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets


# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')


# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'products', views.ProductViewSet)

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^wizard/(?P<slug>[\w-]+)/$', UploadPhotosWizard.as_view([PhotoUploadForm, PhotoSortForm, CartItemForm]), name='wizard'),
    url(r'^wizard/edit/(?P<cart_item_id>\d+)/$', 'photos.views.edit_wizard', name='edit_wizard'),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^accounts/password_change/$', 'django.contrib.auth.views.password_change',
        {'post_change_redirect': '/accounts/password_change/done/'},
        name="password_change"),
    url(r'^accounts/password_change/done/$',
        'django.contrib.auth.views.password_change_done'),

    url(r'^$', 'products.views.home', name='home'),
    url(r'^s/$', 'products.views.search', name='search'),
    url(r'^products/$', 'products.views.all', name='products'),
    url(r'^products/(?P<slug>[\w-]+)/$', 'products.views.single', name='single_product'),

    url(r'^cart/(?P<id>\d+)/$', 'carts.views.remove_from_cart', name='remove_from_cart'),
    url(r'^cart/(?P<slug>[\w-]+)/$', 'carts.views.add_to_cart', name='add_to_cart'),
    url(r'^cart/$', 'carts.views.view', name='cart'),

    url(r'^checkout/$', 'orders.views.checkout', name='checkout'),
    url(r'^orders/$', 'orders.views.orders', name='user_orders'),
    url(r'^ajax/rate_order/$', 'orders.views.rate_order', name='ajax_rate_order'),
    # url(r'^orders/(?P<order_id>[\w-]+)/$', 'orders.views.order_details', name='order_details'),

    url(r'^ajax/dismiss_marketing_message/$', 'marketing.views.dismiss_marketing_message',
        name='dismiss_marketing_message'),
    url(r'^ajax/email_signup/$', 'marketing.views.email_signup', name='ajax_email_signup'),
    url(r'^ajax/add_user_address/$', 'accounts.views.add_user_address', name='ajax_add_user_address'),

    url(r'^accounts/logout/$', 'accounts.views.logout_view', name='auth_logout'),
    url(r'^accounts/login/$', 'accounts.views.login_view', name='auth_login'),
    url(r'^accounts/register/$', 'accounts.views.registration_view', name='auth_register'),
    url(r'^accounts/address/add/$', 'accounts.views.add_user_address', name='add_user_address'),
    url(r'^accounts/activate/(?P<activation_key>\w+)/$', 'accounts.views.activation_view', name='activation_view'),
    url(r'^accounts/profile/$', 'accounts.views.user_profile', name='user_profile'),
    url(r'^address/delete/(?P<address_id>\d+)/$', 'accounts.views.delete_user_address', name='delete_user_address'),
    url(r'^helpticket/send_helpticket/$', 'helptickets.views.send_helpticket', name='send_helpticket'),

    url(r'^photos/upload/$', 'photos.views.upload', name='upload'),
    url(r'^upload2/(?P<slug>[\w-]+)/$', 'photos.views.make', name='upload2'),
    url(r'^make/(?P<slug>[\w-]+)/$', 'photos.views.make', name='make'),
    url(r'^crop/$', 'photos.views.crop_image', name='cropper'),
    url(r'^sort/$', 'photos.views.sort_photos', name='sort_photos'),
    url(r'^delete_uploaded_image/$', 'photos.views.delete_uploaded_image', name='delete_uploaded_image'),

    url(r'^dashboard/$', staff_member_required(AnalyticsIndexView.as_view()), name='dashboard'),
    url(r'^dashboard/orders/$', 'dashboards.views.orders', name='dashboard_orders'),
    url(r'^dashboard/orders/(?P<order_id>[\w-]+)/download/$', 'dashboards.views.send_zipfile', name='send_zipfile'),
    url(r'^dashboard/users/$', 'dashboards.views.users', name='dashboard_users'),
    url(r'^dashboard/reports/$', 'dashboards.views.reports', name='dashboard_reports'),
    url(r'^dashboard/helptickets/$', 'dashboards.views.helptickets', name='dashboard_helptickets'),
    url(r'^dashboard/helptickets/answer/$', 'dashboards.views.answer_help_ticket', name='dashboard_answer_help_ticket'),


    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^upload_from_instagram/(?P<product_slug>[\w-]+)/$', 'photos.views.upload_instagram_images', name='upload_instagram_images'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/models.py
import os

from django.db import models

# Create your models here.
from products.models import Product, Variation


def get_image_path(instance, filename):
    return os.path.join('cart_item/images', str(instance.cart_item), filename)


class Cart(models.Model):
    total = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)

    def __unicode__(self):
        return "Cart id: %s" % self.id


class CartItem(models.Model):
    cart = models.ForeignKey('Cart', null=True, blank=True)
    product = models.ForeignKey(Product)
    variations = models.ManyToManyField(Variation, blank=True)
    quantity = models.IntegerField(default=1)
    line_total = models.DecimalField(default=10.99, max_digits=10, decimal_places=2)
    notes = models.TextField(null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __unicode__(self):
        try:
            return "Cart id: %s" % str(self.cart.id) + " - " + "Product name: %s" % self.product.title
        except:
            return self.product.title

orders/models.py
from decimal import Decimal
from django.conf import settings
from django.db import models

# Create your models here.
from accounts.models import UserAddress
from carts.models import Cart

RATE_CHOICES = zip(range(1, 6), range(1, 6))

STATUS_CHOICES = (
    ("Pendiente", "Pendiente"),
    ("Iniciado", "Iniciado"),
    ("Rechazado", "Rechazado"),
    ("Imprimiendo", "Imprimiendo"),
    ("Enviado", "Enviado"),
)

# python tuples
try:
    tax_rate = settings.DEFAULT_TAX_RATE
except Exception, e:
    print str(e)
    raise NotImplementedError(str(e))


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
    order_id = models.CharField(max_length=120, default='ABC', unique=True)
    cart = models.ForeignKey(Cart)
    status = models.CharField(max_length=120, choices=STATUS_CHOICES, default="Pendiente")
    shipping_address = models.ForeignKey(UserAddress, related_name='shipping_address', default=1)
    billing_address = models.ForeignKey(UserAddress, related_name='billing_address', default=1)
    sub_total = models.DecimalField(default=10.99, max_digits=1000, decimal_places=2)
    tax_total = models.DecimalField(default=0.00, max_digits=1000, decimal_places=2)
    final_total = models.DecimalField(default=10.99, max_digits=1000, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __unicode__(self):
        return self.order_id

    def get_final_amount(self):
        instance = Order.objects.get(id=self.id)
        two_places = Decimal(10) ** -2
        tax_rate_dec = Decimal("%s" % tax_rate)
        sub_total_dec = Decimal(self.sub_total)
        tax_total_dec = Decimal(tax_rate_dec * sub_total_dec).quantize(two_places)
        instance.tax_total = tax_total_dec
        instance.final_total = sub_total_dec + tax_total_dec
        instance.save()
        return instance.final_total


class OrderRating(models.Model):
    order = models.OneToOneField(Order)
    comment = models.TextField(max_length=120)
    rate = models.DecimalField(max_digits=1, decimal_places=0, choices=RATE_CHOICES)

orders/forms.py
from django import forms

from .models import Order, OrderRating

class OrderRatingForm(forms.ModelForm):
    class Meta:
        model = OrderRating
        fields = '__all__'
        error_messages = {
            'comment': {
                'required': "Por favor, ingresa un comentario",
            },
            'rate': {
                'required': "Por favor, ingresa una calificacion",
                'invalid_choice': "Por favor, ingresa una calificacion",
            }
        }

orders/views.py
# coding=utf-8
import time
import json

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.conf import settings
from django.contrib import messages
from django.shortcuts import render, HttpResponseRedirect
from django.http import HttpResponseBadRequest, JsonResponse, Http404
from orders.forms import OrderRatingForm

# Create your views here.

from accounts.forms import UserAddressForm
from accounts.models import UserAddress
from carts.models import Cart

from .models import Order
from .utils import id_generator


def orders(request):
    context = {}
    template = "orders/user.html"
    return render(request, template, context)


# require user login **
@login_required
def checkout(request):
    try:
        the_id = request.session['cart_id']
        cart = Cart.objects.get(id=the_id)
    except:
        the_id = None
        messages.warning(request, "Oops! Aún no has enviado ningún pedido para ser procesado!")
        return HttpResponseRedirect(reverse("cart"))

    try:
        new_order = Order.objects.get(cart=cart)
    except Order.DoesNotExist:
        new_order = Order()
        new_order.cart = cart
        new_order.user = request.user
        new_order.order_id = id_generator()
        new_order.save()
    except:
        new_order = None
        # work on some error message
        messages.warning(request, "Oops! Aún no has enviado ningún pedido para ser procesado!")
        return HttpResponseRedirect(reverse("cart"))
    final_amount = 0
    if new_order is not None:
        new_order.sub_total = cart.total
        new_order.save()
        final_amount = new_order.get_final_amount()

    try:
        address_added = request.GET.get("address_added")
    except:
        address_added = None

    if address_added is None:
        address_form = UserAddressForm()
    else:
        address_form = None

    current_addresses = UserAddress.objects.filter(user=request.user)
    billing_addresses = UserAddress.objects.get_billing_addresses(user=request.user)
    print billing_addresses
    ##1 add shipping address
    ##2 add billing address
    # 3 add and run credit card

    if request.method == "POST":

        try:
            shipping_a = request.POST['default_address']
            # billing_a = request.POST['billing_address']
        except Exception as e:
            print(e)
            shipping_a = request.POST['shipping_address']

        # try:
        #     billing_address_instance = UserAddress.objects.get(id=billing_a)
        # except:
        #     billing_address_instance = None

        try:
            shipping_address_instance = UserAddress.objects.get(id=shipping_a)
        except:
            shipping_address_instance = None

        # if charge["captured"]:
        # new_order.status = "Finished"
        new_order.shipping_address = shipping_address_instance
        # new_order.billing_addresses = billing_address_instance
        new_order.save()
        del request.session['cart_id']
        del request.session['items_total']

        messages.success(request, "Tu pedido ha sido completado! Estaremos en contacto!")

        context = {
            "order": new_order,
            "current_addresses": current_addresses,
            "billing_addresses": billing_addresses,
        }

        return render(request, "orders/order_details.html", context)

    default_address = UserAddress.objects.get(user=User.objects.get(id=1))

    context = {
        "order": new_order,
        "address_form": address_form,
        "default_address": default_address,
        "current_addresses": current_addresses,
        "billing_addresses": billing_addresses,
    }
    template = "orders/checkout.html"
    return render(request, template, context)


def rate_order(request):
    if request.method == "POST":
        form = OrderRatingForm(request.POST)
        if request.is_ajax():
            if form.is_valid():
                form.save()
                messages.success(request, "Tu comentario ha sido enviado. Gracias!")
                # return HttpResponseRedirect(reverse("user_profile"))
                return JsonResponse({'message': 'Success', })
            if form.errors:
                json_data = json.dumps(form.errors)
                return HttpResponseBadRequest(json_data, content_type='application/json')

    else:
        raise Http404


def order_details(request, order_id=None):
    order = Order.objects.get(order_id=order_id)
    context = {'order': order, }
    template = "orders/order_details.html"

    return render(request, template, context)

templates/orders/order_details.html
{% extends "base.html" %}


{% block content %}


<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="text-center">
                <i class="fa fa-search-plus pull-left icon"></i>
                <h2>Pedido # {{ order.order_id }}</h2>
            </div>
            <hr>
            <div class="row">
                <div class="col-xs-12 col-md-3 col-lg-3 pull-left">
                    <div class="panel panel-default height">
                        <div class="panel-heading">Detalles de facturación</div>
                        <div class="panel-body">
                            <strong>{{ order.billing_address.first_name }} {{ order.billing_address.last_name }}</strong><br>
                            {{ order.billing_address.address }}<br>
                            {{ order.billing_address.address2 }}<br>
                            {{ order.billing_address.city }}<br>
                            {{ order.billing_address.country }}<br>
                            {{ order.billing_address.phone }}<br>
                            <strong>{{ order.billing_address.zipcode }}</strong><br>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-md-3 col-lg-3">
                    <div class="panel panel-default height">
                        <div class="panel-heading">Información del pago</div>
                        <div class="panel-body">
                            <strong>Tipo de tarjeta:</strong> Visa<br>
                            <strong>Número de tarjeta:</strong> ***** 332<br>
                            <strong>Fecha de expiración:</strong> 09/2020<br>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-md-3 col-lg-3">
                    <div class="panel panel-default height">
                        <div class="panel-heading">Preferencias del pedido</div>
                        <div class="panel-body">
                            <strong>Regalo?:</strong> No<br>
                            <strong>Envío a casa?:</strong> Si<br>
                            <strong>Insurance:</strong> No<br>
                            <strong>Cupón:</strong> No<br>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-md-3 col-lg-3 pull-right">
                    <div class="panel panel-default height">
                        <div class="panel-heading">Dirección de envío</div>
                        <div class="panel-body">
                            <strong>{{ order.shipping_address.first_name }} {{ order.shipping_address.last_name }}</strong><br>
                            {{ order.shipping_address.address }}<br>
                            {{ order.shipping_address.address2 }}<br>
                            {{ order.shipping_address.city }}<br>
                            {{ order.shipping_address.country }}<br>
                            {{ order.shipping_address.phone }}<br>
                            <strong>{{ order.shipping_address.zipcode }}</strong><br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="text-center"><strong>Resumen del pedido</strong></h3>
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-condensed">
                            <thead>
                                <tr>
                                    <td><strong>Producto</strong></td>
                                    <td class="text-center"><strong>Precio</strong></td>
                                    <td class="text-center"><strong>Cantidad</strong></td>
                                    <td class="text-right"><strong>Total</strong></td>
                                </tr>
                            </thead>
                            <tbody>
                            {% for item in order.cart.cartitem_set.all %}
                                <tr>
                                    <td>{{ item.product.title }}</td>
                                    <td class="text-center">Bs.F {{ item.product.price }}</td>
                                    <td class="text-center">{{ item.quantity }}</td>
                                    <td class="text-right">Bs.F {{ item.line_total }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <button id="print-order" class="btn btn-primary text-center">Imprimir <span class="fa fa-print"></span></button>
        </div>
    </div>
</div>


<style>
.height {
    min-height: 200px;
}

.icon {
    font-size: 47px;
    color: #5CB85C;
}

.iconbig {
    font-size: 77px;
    color: #5CB85C;
}

.table > tbody > tr > .emptyrow {
    border-top: none;
}

.table > thead > tr > .emptyrow {
    border-bottom: none;
}

.table > tbody > tr > .highrow {
    border-top: 3px solid;
}
</style>


{% endblock %}

templates/orders/orders.html
{% extends 'accounts/profile-base.html' %}

{% block orders %}
    <div class="panel panel-primary">
        <div class="panel-heading">Mis Pedidos</div>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Estatus</th>
                    <th>Total</th>
                    <th>Fecha creacion</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            {% for order in user.order_set.all %}
                <tr>
                    <td>
                        <a href="{% url 'order_details' order.order_id %}">{{ order.order_id }}</a>
                    </td>
                    <td>{{ order.status }}</td>
                    <td>{{ order.final_total }}</td>
                    <td>{{ order.timestamp }}</td>
                    <td>
                        {% if not order.orderrating %}
                        <a href="#" data-toggle="modal" data-target="#rateOrderModal"
                           data-order_number="{{ order.order_id }}" data-user="@{{ user.username }}"
                                data-order_id="{{ order.id }}">
                            Que tal estuvo?
                            <span class="glyphicon glyphicon-comment"></span>
                        </a>
                        {% else %}
                            Comentario enviado! =)
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/orders/user.html
{% extends "base.html" %}


{% block content %}


<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="text-center">
                <i class="fa fa-search-plus pull-left icon"></i>
                <h2>Pedido # {{ order.order_id }}</h2>
            </div>
            <hr>
            <div class="row">
                <div class="col-xs-12 col-md-3 col-lg-3 pull-left">
                    <div class="panel panel-default height">
                        <div class="panel-heading">Detalles de facturación</div>
                        <div class="panel-body">
                            <strong>{{ order.user.first_name }} {{ order.user.last_name }}</strong><br>
                            {{ order.billing_address.address }}<br>
                            {{ order.billing_address.address2 }}<br>
                            {{ order.shipping_address.city }}<br>
                            {{ order.shipping_address.country }}<br>
                            {{ order.shipping_address.phone }}<br>
                            <strong>{{ order.shipping_address.zipcode }}</strong><br>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-md-3 col-lg-3">
                    <div class="panel panel-default height">
                        <div class="panel-heading">Información del pago</div>
                        <div class="panel-body">
                            <strong>Tipo de tarjeta:</strong> Visa<br>
                            <strong>Número de tarjeta:</strong> ***** 332<br>
                            <strong>Fecha de expiración:</strong> 09/2020<br>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-md-3 col-lg-3">
                    <div class="panel panel-default height">
                        <div class="panel-heading">Preferencias del pedido</div>
                        <div class="panel-body">
                            <strong>Regalo?:</strong> No<br>
                            <strong>Envío a casa?:</strong> Si<br>
                            <strong>Insurance:</strong> No<br>
                            <strong>Cupón:</strong> No<br>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-md-3 col-lg-3 pull-right">
                    <div class="panel panel-default height">
                        <div class="panel-heading">Dirección de envío</div>
                        <div class="panel-body">
                            <strong>{{ order.user.first_name }} {{ order.user.last_name }}</strong><br>
                            {{ order.shipping_address.address }}<br>
                            {{ order.shipping_address.address2 }}<br>
                            {{ order.shipping_address.city }}<br>
                            {{ order.shipping_address.country }}<br>
                            {{ order.shipping_address.phone }}<br>
                            <strong>{{ order.shipping_address.zipcode }}</strong><br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="text-center"><strong>Resumen del pedido</strong></h3>
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-condensed">
                            <thead>
                                <tr>
                                    <td><strong>Producto</strong></td>
                                    <td class="text-center"><strong>Precio</strong></td>
                                    <td class="text-center"><strong>Cantidad</strong></td>
                                    <td class="text-right"><strong>Total</strong></td>
                                </tr>
                            </thead>
                            <tbody>
                            {% for item in order.cart.cartitem_set.all %}
                                <tr>
                                    <td>{{ item.product.title }}</td>
                                    <td class="text-center">Bs.F {{ item.product.price }}</td>
                                    <td class="text-center">{{ item.quantity }}</td>
                                    <td class="text-right">{{ item.line_total }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
.height {
    min-height: 200px;
}

.icon {
    font-size: 47px;
    color: #5CB85C;
}

.iconbig {
    font-size: 77px;
    color: #5CB85C;
}

.table > tbody > tr > .emptyrow {
    border-top: none;
}

.table > thead > tr > .emptyrow {
    border-bottom: none;
}

.table > tbody > tr > .highrow {
    border-top: 3px solid;
}
</style>


{% endblock %}